export const categoriesData = [
  {id: 1, name: 'Jollibee', image: require('../../assets/imgs/jollibee.jpg')},
  {id: 2, name: 'Mcdonalds', image: require('../../assets/imgs/mcdonalds.jpg')},
  {id: 3, name: 'Chowking', image: require('../../assets/imgs/chowking.jpg')},
  {id: 4, name: 'KFC', image: require('../../assets/imgs/kfc.jpg')},
  {
    id: 5,
    name: 'Mang Inasal',
    image: require('../../assets/imgs/mang-inasal.png'),
  },
  {id: 6, name: 'Greenwich', image: require('../../assets/imgs/greenwich.jpg')},
  {
    id: 7,
    name: 'Dunkin Donuts',
    image: require('../../assets/imgs/donuts.jpg'),
  },
];

export const restaurantsData = [
  {
    id: 0,
    restaurantName: 'McDonalds',
    farAway: '21.2',
    businessAddress: '22 Bessie Street, Cape Town',
    image: require('../../assets/imgs/mcdonalds.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.18886712, lon: 28.246325},
    discount: 10,
    deliveryTime: 15,
    productData: [
      {
        name: 'Hand cut chips',
        price: 29,
        image: '',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: '',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: '',
      },
    ],
  },
  {
    id: 1,
    restaurantName: 'KFC',
    farAway: '21.2',
    businessAddress: '22 Bessie Street, Cape Town',
    image: require('../../assets/imgs/kfc.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.18886712, lon: 28.246325},
    discount: 10,
    deliveryTime: 15,
    productData: [
      {
        name: 'Hand cut chips',
        price: 29,
        image: '',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: '',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: '',
      },
    ],
  },
  {
    id: 2,
    restaurantName: 'Jollibee',
    farAway: '21.2',
    businessAddress: '22 Bessie Street, Cape Town',
    image: require('../../assets/imgs/jollibee.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.18886712, lon: 28.246325},
    discount: 10,
    deliveryTime: 15,
    productData: [
      {
        name: 'Hand cut chips',
        price: 29,
        image: '',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: '',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: '',
      },
    ],
  },
  {
    id: 3,
    restaurantName: 'Mang Inasal',
    farAway: '21.2',
    businessAddress: '22 Bessie Street, Cape Town',
    image: require('../../assets/imgs/mang-inasal.png'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.18886712, lon: 28.246325},
    discount: 10,
    deliveryTime: 15,
    productData: [
      {
        name: 'Hand cut chips',
        price: 29,
        image: '',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: '',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: '',
      },
    ],
  },
  {
    id: 4,
    restaurantName: 'Chowking',
    farAway: '21.2',
    businessAddress: '22 Bessie Street, Cape Town',
    image: require('../../assets/imgs/chowking.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.18886712, lon: 28.246325},
    discount: 10,
    deliveryTime: 15,
    productData: [
      {
        name: 'Hand cut chips',
        price: 29,
        image: '',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: '',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: '',
      },
    ],
  },
  {
    id: 5,
    restaurantName: 'Greenwich',
    farAway: '21.2',
    businessAddress: '22 Bessie Street, Cape Town',
    image: require('../../assets/imgs/greenwich.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.18886712, lon: 28.246325},
    discount: 10,
    deliveryTime: 15,
    productData: [
      {
        name: 'Hand cut chips',
        price: 29,
        image: '',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: '',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: '',
      },
    ],
  },
  {
    id: 6,
    restaurantName: 'Dunkin Donuts',
    farAway: '21.2',
    businessAddress: '22 Bessie Street, Cape Town',
    image: require('../../assets/imgs/donuts.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.18886712, lon: 28.246325},
    discount: 10,
    deliveryTime: 15,
    productData: [
      {
        name: 'Hand cut chips',
        price: 29,
        image: '',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: '',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: '',
      },
    ],
  },
];
